### ISSUE TITLE
[BUG] 403 Forbidden Error When Mapping 'all_access' Role to LDAP Group in OpenSearch

### ISSUE THREAD

**Issue by yoicomment** [opensearch-project/terraform-provider-opensearch#153]
# What is the bug?
When attempting to map the "all_access" predefined role in OpenSearch to an LDAP group, the process fails and results in an error. The specific error message received is "Error: elastic: Error 403 (Forbidden)". This suggests a permission issue, but the exact cause is unclear.

# How can one reproduce the bug?
1. Set up OpenSearch with LDAP authc and authz.
2. Attempt to map the "all_access" predefined role to an LDAP group through the OpenSearch security configuration.
3. Observe that the mapping does not succeed and results in the aforementioned error message.
# What is the expected behavior?
The expected behavior is that the "all_access" role should successfully map to the specified LDAP group, granting members of this group the appropriate access permissions within OpenSearch.

What is your host/environment?
[Please provide details about your operating system, version of OpenSearch, and any other relevant environment details.]
- Ubuntu 22.04
- OpenSearch version 2.11.1 (runs as docker containers)

# Do you have any additional context?
```
resource "opensearch_roles_mapping" "mapper" {
  role_name   = "all_access"
  description = "Mapping all_access role to ldap group"
  backend_roles = ["ldap_group"]
}
```

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @yoicomment Looks similar https://github.com/opensearch-project/terraform-provider-opensearch/issues/158, https://github.com/opensearch-project/terraform-provider-opensearch/issues/156 .

Adding @rblcoder @bbarani

**Comment by rblcoder** [comment]
@yoicomment You would also need to specify any existing users and backend_roles for the role mapping in the terraform code.

**Comment by yoicomment** [comment]
```
resource "opensearch_roles_mapping" "mapper" {
  role_name   = "all_access"
  description = "Mapping all_access role to ldap group"
  backend_roles = ["ldap_group"]
}
```

As you can see, I specified "ldap_group" as "backend_roles". Shouldn't that be enough? I don't want to assign "all_access" to users explicitely.

Besides that, I found a security setting:

![image](https://github.com/opensearch-project/terraform-provider-opensearch/assets/145778425/8cc90347-8b8d-4f11-acff-c95d4e821c3a)

Does it fail because it is set to the default value?

**Comment by rblcoder** [comment]
@yoicomment The user you are authenticating with from the Terraform OpenSearch provider would continue to need access if you are using HTTP basic auth. Are you using HTTP basic auth?

**Comment by yoicomment** [comment]
Yes, I'm using the admin user for that

**Comment by rblcoder** [comment]
@yoicomment I too get 403 error if I remove admin from the role mapping for the following configuration as admin is a user from the internal user database and loses access if it is not part of the role mapping.

```
terraform {
  required_providers {
    opensearch = {
      source = "opensearch-project/opensearch"
      version = "2.2.0"
    }
  }
}

provider "opensearch" {
  url = "https://localhost:9200"
  username          = "admin"
  password          = "admin"
  insecure = true

  version_ping_timeout = "10"

}

resource "opensearch_roles_mapping" "mapper" {
  role_name   = "all_access"
  description = "Mapping all_access role to ldap group"
  backend_roles = ["admin", "Administrator"]
}
```

**Comment by yoicomment** [comment]
This is my "internal_users.yml" file.


```
_meta:
  type: "internalusers"
  config_version: 2

# Define your internal users here

admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"
```

This is my "roles_mapping.yml" file:

```
_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Maps admin to all_access"
```

I use this for:

```
provider "opensearch" {
  url = "https://localhost:9200"
  username          = "admin"
  password          = "admin"
}
```

The name of the ldap group is:

> all_admins

Now, I wanna assign the role to this ldap group:

```
resource "opensearch_roles_mapping" "mapper" {
  role_name   = "all_access"
  description = "Mapping all_access role to ldap group"
  backend_roles = ["all_admins"]
}
```

And this does not work for me.
